name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: clone_criterion
      run: git clone --recursive https://github.com/Snaipe/Criterion
    - name: make_criterion
      run: meson build
      run: ninja -C build
    - name: make
      run: make
    - name: tests_run
      run: make tests_run
